---
label: Project
hide_body: false
fields:
- type: image_gallery
  name: photos
  label: Photos
- type: boolean
  name: showInHomePage
  label: Show in Home Page
- type: boolean
  name: outOfStock
  label: Out of Stock
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
pages:
- projects/3d-graff.md
- projects/alice-in-wonderland.md
- projects/arlekin.md
- projects/black-charm.md
- projects/coasters.md
- projects/coffe-and-more.md
- projects/desk-and-image.md
- projects/doves.md
- projects/dutches.md
- projects/eye-in-your-salad.md
- projects/garden.md
- projects/hurt-on-a-box.md
- projects/like-versace.md
- projects/mask-2.md
- projects/mask.md
- projects/queen-2.md
- projects/queen.md
- projects/red-hair.md
- projects/rised-stencil.md
- projects/romance.md
- projects/royal.md
- projects/salt-and-paper.md
- projects/sea.md
- projects/thunderbolt.md
- projects/twins.md
- projects/waves-on-glass.md
- projects/white-flowers.md
