---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: boolean
  name: wide
  label: Wide Thumbnail
  description: This project will take the space of 2 projects on the grid!
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
pages:
- projects/3d-graff.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
