---
label: Project
hide_body: false
fields:
- type: image_gallery
  name: photos
  label: Photos
- type: boolean
  name: showInHomePage
  label: Show in Home Page
- type: boolean
  name: outOfStock
  label: Out of Stock
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
pages:
- projects/3d-graff.md
- projects/4-seasons.md
- projects/agly-duckling.md
- projects/alice-in-wonderland.md
- projects/almost-dark.md
- projects/arlekin.md
- projects/black-charm.md
- projects/black-princess.md
- projects/bunny...in-wonderland.md
- projects/change-the-rocks.md
- projects/clock-a.k.md
- projects/coasters.md
- projects/coffe-and-more.md
- projects/desk-and-image.md
- projects/doves.md
- projects/dutches.md
- projects/eye-in-your-salad.md
- projects/flowers-on-bag.md
- projects/from-death...to-life.md
- projects/garden.md
- projects/hurt-on-a-box.md
- projects/i-am-not-a-volcano.md
- projects/i-dont-need-flowers.md
- projects/iris.md
- projects/iron-charm.md
- projects/jewerly-box-3.md
- projects/jewerly-box-4.md
- projects/leopard.md
- projects/like-japaness.md
- projects/like-versace.md
- projects/mask-2.md
- projects/mask.md
- projects/new-kitchen.md
- projects/new-living-room.md
- projects/old-door-new-life.md
- projects/queen-2.md
- projects/queen.md
- projects/reborn-as-green.md
- projects/red-hair.md
- projects/rised-stencil.md
- projects/romance.md
- projects/royal.md
- projects/salt-and-paper.md
- projects/sea.md
- projects/smokey-wall.md
- projects/something-simple.md
- projects/the-green-box.md
- projects/the-yellow-win.md
- projects/thunderbolt.md
- projects/twins.md
- projects/wall.md
- projects/waves-on-glass.md
- projects/white-flowers.md
