---
label: Project
hide_body: false
fields:
- type: image_gallery
  name: photos
  label: Photos
- type: boolean
  name: showInHomePage
  label: Show in Home Page
- type: boolean
  name: outOfStock
  label: Out of Stock
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
pages:
- projects/3d-graff.md
- projects/alice-in-wonderland.md
- projects/mask-2.md
- projects/mask.md
- projects/pearl.md
- projects/queen.md
- projects/royal.md
