---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: 'Η αλήθεια είναι άσχημη. Και έχουμε την τέχνη για να μη μας σκοτώσει η αλήθεια.Φ.
    Νίτσε '
- type: textarea
  name: hero_title
  config:
    wysiwyg: true
    schema:
      format: html
  label: 'Η αλήθεια είναι άσχημη. Και έχουμε την τέχνη για να μη μας σκοτώσει η αλήθεια.Φ.
    Νίτσε '
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
- name: contact_email
  label: Contact email
  type: text
- name: youtube_url
  label: Contact email
  type: text
- name: facebook_url
  label: Contact email
  type: text
- name: instagram_url
  label: Contact email
  type: text
- name: pinterest_url
  label: Contact email
  type: text
pages:
- data/theme.json
